In [4]:
from sklearn.ensemble import RandomForestClassifier

In [5]:
from numpy import genfromtxt, savetxt

In [6]:
# def main():
    #create the training & test sets, skipping the header row with [1:]
dataset = genfromtxt(open('Data/train.csv','rb'), delimiter=',', dtype='f8')[1:]

In [7]:
target = [x[0] for x in dataset]
train = [x[1:] for x in dataset]
test = genfromtxt(open('Data/test.csv','rb'), delimiter=',', dtype='f8')[1:]

    #create and train the random forest
    #multi-core CPUs can use: rf = RandomForestClassifier(n_estimators=100, n_jobs=2)
rf = RandomForestClassifier(n_estimators=100)
rf.fit(train, target)
predicted_probs = [x[1] for x in rf.predict_proba(test)]

savetxt('Data/submission.csv', predicted_probs, delimiter=',', fmt='%f')

[0.87,
 0.91000000000000003,
 0.58999999999999997,
 0.98999999999999999,
 0.16,
 0.58999999999999997,
 0.93999999999999995,
 0.67000000000000004,
 0.87,
 0.59999999999999998,
 0.35999999999999999,
 0.68999999999999995,
 0.78000000000000003,
 0.56000000000000005,
 0.37,
 0.16,
 0.27000000000000002,
 0.23000000000000001,
 0.47999999999999998,
 0.72999999999999998,
 0.19,
 0.84999999999999998,
 0.88,
 0.93999999999999995,
 0.87,
 0.56999999999999995,
 0.089999999999999997,
 0.23000000000000001,
 0.28000000000000003,
 0.54000000000000004,
 0.32000000000000001,
 0.11,
 0.72999999999999998,
 0.46999999999999997,
 0.51000000000000001,
 0.92000000000000004,
 0.72999999999999998,
 0.68000000000000005,
 0.88,
 0.95999999999999996,
 0.46999999999999997,
 0.059999999999999998,
 0.64000000000000001,
 0.91000000000000003,
 0.10000000000000001,
 0.34999999999999998,
 0.82999999999999996,
 0.47999999999999998,
 0.94999999999999996,
 0.58999999999999997,
 0.80000000000000004,
 0.089999999999999997,
 0.

In [21]:
train

[array([ 0.        ,  0.49700901,  0.1       , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.36666667,  0.60629148,  0.05      , ...,  0.        ,
         1.        ,  0.        ]),
 array([ 0.0333    ,  0.48012427,  0.        , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.        ,  0.53882479,  0.        , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.1       ,  0.51779435,  0.        , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.13333333,  0.77103455,  0.2       , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.0667    ,  0.56740148,  0.1       , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.13333333,  0.61005673,  0.15      , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.        ,  0.77681636,  0.05      , ...,  0.        ,
         0.        ,  0.        ]),
 array([ 0.1       ,  0.76814957,  0.1       , ...,  0.        ,
         0.        ,  0.  

NameError: name 'dataset' is not defined